name: apexhelper
description: A helper tool for Apex Legends

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

flutter_icons:
  android: true
  ios: false
  image_path_android: assets/icon/icon.png
  image_path_ios: assets/icon/icon.png
  adaptive_icon_background: assets/icon/background.png
  adaptive_icon_foreground: assets/icon/foreground.png

dependencies:
  flutter_youtube: "^1.1.4"
  photo_view: ^0.1.3
  flutter_launcher_icons: ^0.7.0
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons. 
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/bangalore.jpg
   - assets/images/bloodhound.jpg
   - assets/images/caustic.jpg
   - assets/images/gibraltar.jpg
   - assets/images/lifeline.jpg
   - assets/images/mirage.jpg
   - assets/images/pathfinder.jpg
   - assets/images/wraith.jpg
   - assets/images/bangalore_thumb.png
   - assets/images/bloodhound_thumb.png
   - assets/images/caustic_thumb.png
   - assets/images/gibraltar_thumb.png
   - assets/images/lifeline_thumb.png
   - assets/images/mirage_thumb.png
   - assets/images/pathfinder_thumb.png
   - assets/images/wraith_thumb.png

   - assets/images/weapons/assault/flatline_thumb.png
   - assets/images/weapons/assault/flatline.jpg
   - assets/images/weapons/assault/hemlock_thumb.png
   - assets/images/weapons/assault/hemlock.jpg
   - assets/images/weapons/assault/r301_thumb.png
   - assets/images/weapons/assault/r301.jpg

   - assets/images/weapons/lmg/devotion_thumb.png
   - assets/images/weapons/lmg/devotion.jpg
   - assets/images/weapons/lmg/spitfire.jpg #! Thumbnail

   - assets/images/weapons/pistol/p2020_thumb.png
   - assets/images/weapons/pistol/p2020.jpg
   - assets/images/weapons/pistol/re45_thumb.png
   - assets/images/weapons/pistol/re45.jpg
   - assets/images/weapons/pistol/wingman_thumb.png
   - assets/images/weapons/pistol/wingman.jpg

   - assets/images/weapons/shotgun/eva8_thumb.png
   - assets/images/weapons/shotgun/eva8.jpg
   - assets/images/weapons/shotgun/mastiff.jpg
   - assets/images/weapons/shotgun/mozambique.jpg
   - assets/images/weapons/shotgun/mozambique_thumb.png
   - assets/images/weapons/shotgun/peacekeeper_thumb.png
   - assets/images/weapons/shotgun/peacekeeper.jpg

   - assets/images/weapons/smg/alternator_thumb.png
   - assets/images/weapons/smg/alternator.jpg
   - assets/images/weapons/smg/prowler_thumb.png
   - assets/images/weapons/smg/prowler.jpg
   - assets/images/weapons/smg/r99.jpg #! Thumbnail

   - assets/images/weapons/sniper/scout_thumb.png
   - assets/images/weapons/sniper/scout.jpg
   - assets/images/weapons/sniper/kraber.jpg #! Thumbnail
   - assets/images/weapons/sniper/longbow.jpg #! Thumbnail
   - assets/images/weapons/sniper/tripletake.jpg #! Thumbnail

   - assets/images/map.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family:  Custom
        fonts:
          - asset: assets/fonts/Custom.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
